import os
from fpdf import FPDF
from datetime import datetime
from uuid import uuid4

class ReportAgent:
    def __init__(self, output_dir: str = "reports_output"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_report(self, workspace_name: str, documents: list, sections: list, metrics_data: list, red_flags_data: list) -> str:
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        def sanitize_text(text: str) -> str:
            if not text: return ""
            text = str(text)
            # Replace common smart quotes/dashes to prevent latin-1 encoding issues
            text = text.replace('\u201c', '"').replace('\u201d', '"').replace('\u2018', "'").replace('\u2019', "'").replace('\u2013', '-').replace('\u2014', '-')
            # Ensure latin-1 encoding
            text = text.encode('latin-1', 'replace').decode('latin-1')
            # Break up extremely long words that would crash FPDF
            words = text.split(' ')
            wrapped = []
            for w in words:
                if len(w) > 30:
                    w = '-'.join(w[i:i+30] for i in range(0, len(w), 30))
                wrapped.append(w)
            return ' '.join(wrapped)

        workspace_name = sanitize_text(workspace_name)
        
        # Title Page
        pdf.add_page()
        pdf.set_font("helvetica", "B", 24)
        pdf.cell(0, 20, "AstraFinance AI Report", ln=True, align="C")
        pdf.set_font("helvetica", "I", 14)
        pdf.cell(0, 10, f"Workspace: {workspace_name}", ln=True, align="C")
        pdf.set_font("helvetica", "", 12)
        pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%B %d, %Y')}", ln=True, align="C")
        pdf.ln(20)

        # Included Documents
        pdf.set_font("helvetica", "B", 16)
        pdf.cell(0, 10, "Included Documents", ln=True)
        pdf.set_font("helvetica", "", 12)
        for doc in documents:
            pdf.cell(0, 10, f"- {sanitize_text(doc.get('name', 'Unknown'))}", ln=True)
        pdf.ln(10)
        
        for section in sections:
            pdf.add_page()
            sec_id = section.get("id")
            sec_label = sanitize_text(section.get("label", sec_id))
            
            pdf.set_font("helvetica", "B", 18)
            pdf.cell(0, 15, sec_label, ln=True)
            pdf.set_font("helvetica", "", 12)

            if sec_id == "exec_summary":
                pdf.multi_cell(0, 10, "This executive summary has been automatically generated by AstraFinance AI based on the selected financial documents. It highlights key performance metrics and identified risks.")
                
            elif sec_id == "financial_overview":
                if metrics_data:
                    for metric in metrics_data:
                        # Extract key metrics
                        key_metrics = metric.get("key_metrics", [])
                        if key_metrics:
                            pdf.set_font("helvetica", "B", 14)
                            pdf.cell(0, 10, "Extracted Metrics", ln=True)
                            pdf.set_font("helvetica", "", 12)
                            for km in key_metrics:
                                name = sanitize_text(km.get('name', 'N/A'))
                                val = sanitize_text(km.get('value', 'N/A'))
                                pdf.multi_cell(0, 10, f"{name}: {val}")
                else:
                    pdf.multi_cell(0, 10, "No financial metrics found in the selected documents.")

            elif sec_id == "financial_performance":
                if metrics_data:
                    for metric in metrics_data:
                        trends = metric.get("trends", [])
                        if trends:
                            pdf.set_font("helvetica", "B", 14)
                            pdf.cell(0, 10, "Financial Performance Trends", ln=True)
                            pdf.set_font("helvetica", "", 12)
                            for trend in trends:
                                name = sanitize_text(trend.get('metric', trend.get('name', 'N/A')))
                                val = sanitize_text(trend.get('value', 'N/A'))
                                change = sanitize_text(trend.get('change', ''))
                                line = f"{name}: {val}"
                                if change:
                                    line += f" ({change})"
                                pdf.multi_cell(0, 10, line)
                        else:
                            key_metrics = metric.get("key_metrics", [])
                            if key_metrics:
                                pdf.set_font("helvetica", "B", 14)
                                pdf.cell(0, 10, "Key Performance Indicators", ln=True)
                                pdf.set_font("helvetica", "", 12)
                                for km in key_metrics:
                                    name = sanitize_text(km.get('name', 'N/A'))
                                    val = sanitize_text(km.get('value', 'N/A'))
                                    pdf.multi_cell(0, 10, f"{name}: {val}")
                else:
                    pdf.multi_cell(0, 10, "No financial performance data found in the selected documents.")

            elif sec_id == "risk_analysis":
                if red_flags_data:
                    for flag in red_flags_data:
                        pdf.set_font("helvetica", "B", 12)
                        pdf.cell(0, 10, f"Risk: {sanitize_text(flag.get('title', 'Unknown'))}", ln=True)
                        pdf.set_font("helvetica", "", 11)
                        pdf.multi_cell(0, 8, f"Description: {sanitize_text(flag.get('description', ''))}")
                        pdf.multi_cell(0, 8, f"Severity: {sanitize_text(flag.get('severity', 'Unknown'))} | Confidence: {flag.get('confidence_score', 0)}")
                        pdf.ln(5)
                else:
                    pdf.multi_cell(0, 10, "No red flags or significant risks were detected in the selected documents.")

            elif sec_id == "comparative_analysis":
                pdf.multi_cell(0, 10, "Comparative analysis is based on the selected documents. If multiple companies were selected, their key metrics would be contrasted here.")

            elif sec_id == "ai_insights":
                pdf.multi_cell(0, 10, "AI Insights: The documents suggest a stable financial footing but with specific risks highlighted in the risk section that warrant further investigation.")

            elif sec_id == "conclusion":
                pdf.multi_cell(0, 10, "Conclusion: This concludes the AstraFinance AI report. Always verify automated insights with raw financial statements.")

            else:
                pdf.multi_cell(0, 10, f"Content for {sec_label} is dynamically compiled based on document data.")

        # Save PDF
        file_name = f"report_{uuid4().hex}.pdf"
        file_path = os.path.join(self.output_dir, file_name)
        pdf.output(file_path)
        
        return file_path

report_agent = ReportAgent()
